//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authority) DeepCopyInto(out *Authority) {
	*out = *in
	if in.Reads != nil {
		in, out := &in.Reads, &out.Reads
		*out = make([]AuthorityRead, len(*in))
		copy(*out, *in)
	}
	if in.MaxTaskDurationSeconds != nil {
		in, out := &in.MaxTaskDurationSeconds, &out.MaxTaskDurationSeconds
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authority.
func (in *Authority) DeepCopy() *Authority {
	if in == nil {
		return nil
	}
	out := new(Authority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorityRead) DeepCopyInto(out *AuthorityRead) {
	*out = *in
	out.GVK = in.GVK
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorityRead.
func (in *AuthorityRead) DeepCopy() *AuthorityRead {
	if in == nil {
		return nil
	}
	out := new(AuthorityRead)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBinding) DeepCopyInto(out *CapabilityBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBinding.
func (in *CapabilityBinding) DeepCopy() *CapabilityBinding {
	if in == nil {
		return nil
	}
	out := new(CapabilityBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapabilityBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBindingList) DeepCopyInto(out *CapabilityBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapabilityBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBindingList.
func (in *CapabilityBindingList) DeepCopy() *CapabilityBindingList {
	if in == nil {
		return nil
	}
	out := new(CapabilityBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapabilityBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBindingSpec) DeepCopyInto(out *CapabilityBindingSpec) {
	*out = *in
	out.ServiceRef = in.ServiceRef
	out.ServiceAgentRef = in.ServiceAgentRef
	if in.Knowledge != nil {
		in, out := &in.Knowledge, &out.Knowledge
		*out = new(Knowledge)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = new(Tools)
		(*in).DeepCopyInto(*out)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]Skill, len(*in))
		copy(*out, *in)
	}
	if in.Authority != nil {
		in, out := &in.Authority, &out.Authority
		*out = new(Authority)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBindingSpec.
func (in *CapabilityBindingSpec) DeepCopy() *CapabilityBindingSpec {
	if in == nil {
		return nil
	}
	out := new(CapabilityBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBindingStatus) DeepCopyInto(out *CapabilityBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBindingStatus.
func (in *CapabilityBindingStatus) DeepCopy() *CapabilityBindingStatus {
	if in == nil {
		return nil
	}
	out := new(CapabilityBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GVKRef) DeepCopyInto(out *GVKRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GVKRef.
func (in *GVKRef) DeepCopy() *GVKRef {
	if in == nil {
		return nil
	}
	out := new(GVKRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Knowledge) DeepCopyInto(out *Knowledge) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]KnowledgeSource, len(*in))
		copy(*out, *in)
	}
	if in.Concepts != nil {
		in, out := &in.Concepts, &out.Concepts
		*out = make([]KnowledgeConcept, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Knowledge.
func (in *Knowledge) DeepCopy() *Knowledge {
	if in == nil {
		return nil
	}
	out := new(Knowledge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeConcept) DeepCopyInto(out *KnowledgeConcept) {
	*out = *in
	out.GVK = in.GVK
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeConcept.
func (in *KnowledgeConcept) DeepCopy() *KnowledgeConcept {
	if in == nil {
		return nil
	}
	out := new(KnowledgeConcept)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeSource) DeepCopyInto(out *KnowledgeSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeSource.
func (in *KnowledgeSource) DeepCopy() *KnowledgeSource {
	if in == nil {
		return nil
	}
	out := new(KnowledgeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServer) DeepCopyInto(out *MCPServer) {
	*out = *in
	in.ToolSelector.DeepCopyInto(&out.ToolSelector)
	if in.Mutating != nil {
		in, out := &in.Mutating, &out.Mutating
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServer.
func (in *MCPServer) DeepCopy() *MCPServer {
	if in == nil {
		return nil
	}
	out := new(MCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ref) DeepCopyInto(out *Ref) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ref.
func (in *Ref) DeepCopy() *Ref {
	if in == nil {
		return nil
	}
	out := new(Ref)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skill) DeepCopyInto(out *Skill) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skill.
func (in *Skill) DeepCopy() *Skill {
	if in == nil {
		return nil
	}
	out := new(Skill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSelector) DeepCopyInto(out *ToolSelector) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSelector.
func (in *ToolSelector) DeepCopy() *ToolSelector {
	if in == nil {
		return nil
	}
	out := new(ToolSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tools) DeepCopyInto(out *Tools) {
	*out = *in
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]MCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tools.
func (in *Tools) DeepCopy() *Tools {
	if in == nil {
		return nil
	}
	out := new(Tools)
	in.DeepCopyInto(out)
	return out
}
