// src/usage/to-cloud-event.ts
//
// LIFTED VERBATIM from cloud-portal main:app/modules/usage/to-cloud-event.ts
// -----------------------------------------------------------------------
//
// Convert the service's internal `UsageEvent` shape into the CloudEvents
// v1.0 envelope the billing Ingestion Gateway requires. This is the
// single seam between service-internal data and the platform wire
// format — every field the gateway validates is set here.
//
// Validation rules (billing/internal/gateway/validate/validate.go):
//   - id is the UsageEvent's ULID (already generated by ulid())
//   - subject = `projects/{name}` (NOT a /-suffixed path)
//   - datacontenttype = "application/json" exactly
//   - data.value is a base-10 INT64 string
//
// Anything that fails those checks is rejected with HTTP 400 in batch
// mode and surfaces as `MULTI_STATUS` per-event in the response.
import type { CloudEvent, UsageEvent } from './types';

export interface ToCloudEventOptions {
  /**
   * URI identifying the producer. CloudEvents spec is permissive — any
   * URI-reference is acceptable — but using the service URL makes it
   * easy to grep for emitter origin in the gateway logs.
   */
  source: string;
}

export function toCloudEvent(event: UsageEvent, opts: ToCloudEventOptions): CloudEvent {
  return {
    id: event.eventID,
    specversion: '1.0',
    type: event.meterName,
    source: opts.source,
    subject: `projects/${event.projectRef.name}`,
    datacontenttype: 'application/json',
    time: event.timestamp,
    data: {
      value: event.value,
      ...(Object.keys(event.dimensions).length > 0 ? { dimensions: event.dimensions } : {}),
      resource: {
        group: event.resource.ref.group,
        kind: event.resource.ref.kind,
        namespace: event.resource.ref.namespace,
        name: event.resource.ref.name,
        ...(event.resource.ref.uid ? { uid: event.resource.ref.uid } : {}),
      },
    },
  };
}
