apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: assistant-consumer-ui-plugin
    app.kubernetes.io/name: assistant-consumer-ui-plugin
  name: assistant-consumer-ui-plugin
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: assistant-consumer-ui-plugin
    app.kubernetes.io/name: assistant-consumer-ui-plugin
