apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stub-llm.yaml
  - llm-backend.yaml
  - aigatewayroute.yaml
configMapGenerator:
  - name: stub-llm-src
    namespace: patch-playground
    files:
      - stub-llm.mjs
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: agent-framework-playground
