//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AssistantEndpoint) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.AssistantEndpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AssistantEndpointList) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.AssistantEndpointList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AssistantEndpointSpec) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.AssistantEndpointSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CapabilityGapReport) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.CapabilityGapReport"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CapabilityGapReportList) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.CapabilityGapReportList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CapabilityGapReportStatus) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.CapabilityGapReportStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Conversation) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.Conversation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationList) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationMessage) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationMessage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationMessages) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationMessages"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationStatus) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationStatus"
}
