//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Conversation) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.Conversation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationList) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationMessage) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationMessage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationMessages) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationMessages"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ConversationStatus) OpenAPIModelName() string {
	return "com.miloapis.assistant.pkg.apis.assistant.v1alpha1.ConversationStatus"
}
